input_features:
    -
        name: Size
        type: numerical
        preprocessing:
          missing_value_strategy: fill_with_mean
    -
        name: Bedrooms
        type: numerical
        preprocessing:
          missing_value_strategy: fill_with_mean


output_features:
    -
        name: Price
        type: numerical
